/**
 * Rich demo dataset for `Clients` when `VITE_APKZIO_DATA_SOURCE=mock`.
 * Does not call the API — illustrates enterprise CRM density in screenshots and reviews.
 */
import type { AdminClientDetail, AdminClientSummary } from "@/lib/api";

export const ADMIN_CLIENTS_DEMO: AdminClientSummary[] = [
  {
    id: "demo-client-northwind",
    email: "operations@northwind.mobile",
    full_name: "Jordan Lee",
    plan: "enterprise",
    email_verified: true,
    created_at: new Date(Date.now() - 86400000 * 210).toISOString(),
    last_seen_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    google_linked: true,
    apps_count: 12,
    builds_count: 184,
    active_subscriptions: 2,
    lifetime_revenue: 428_900,
    account_status: "active",
  },
  {
    id: "demo-client-aurora",
    email: "growth@aurora.health",
    full_name: "Samira Patel",
    plan: "business",
    email_verified: true,
    created_at: new Date(Date.now() - 86400000 * 94).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    google_linked: false,
    apps_count: 4,
    builds_count: 52,
    active_subscriptions: 1,
    lifetime_revenue: 62_400,
    account_status: "active",
  },
  {
    id: "demo-client-lumen",
    email: "cto@lumen-io.dev",
    full_name: "Chris Okonkwo",
    plan: "pro",
    email_verified: true,
    created_at: new Date(Date.now() - 86400000 * 402).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000 * 88).toISOString(),
    google_linked: true,
    apps_count: 2,
    builds_count: 28,
    active_subscriptions: 0,
    lifetime_revenue: 18_200,
    account_status: "churned",
  },
  {
    id: "demo-client-pilot",
    email: "founder@pixelpulse.app",
    full_name: "Taylor Brooks",
    plan: "starter",
    email_verified: false,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    google_linked: false,
    apps_count: 0,
    builds_count: 3,
    active_subscriptions: 0,
    lifetime_revenue: 0,
    account_status: "lead",
  },
];

export const ADMIN_CLIENT_DETAIL_DEMO: Record<string, AdminClientDetail> = {
  "demo-client-northwind": {
    summary: ADMIN_CLIENTS_DEMO[0]!,
    profile: {
      id: "demo-client-northwind",
      email: "operations@northwind.mobile",
      full_name: "Jordan Lee",
      plan: "enterprise",
      email_verified: true,
      created_at: ADMIN_CLIENTS_DEMO[0]!.created_at,
      phone: "+1 (415) 555-0199",
      location: "San Francisco, CA",
      website: "https://northwind.example",
      bio: "Fleet operations — 40 markets, phased APK rollout.",
    },
    apps: [
      {
        id: "demo-app-a",
        name: "Northwind Driver",
        package_name: "com.northwind.driver",
        status: "active",
        created_at: new Date(Date.now() - 86400000 * 120).toISOString(),
      },
      {
        id: "demo-app-b",
        name: "Northwind Partner",
        package_name: "com.northwind.partner",
        status: "active",
        created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
      },
    ],
    builds: [
      {
        id: "demo-build-1",
        app_id: "demo-app-a",
        version_name: "3.12.0",
        version_code: 31200,
        status: "success",
        build_started_at: new Date(Date.now() - 3600000 * 5).toISOString(),
        build_completed_at: new Date(Date.now() - 3600000 * 4.5).toISOString(),
      },
      {
        id: "demo-build-2",
        app_id: "demo-app-b",
        version_name: "1.4.2",
        version_code: 10402,
        status: "building",
        build_started_at: new Date(Date.now() - 600000).toISOString(),
        build_completed_at: null,
      },
    ],
    subscriptions: [
      {
        id: "sub-1",
        plan_name: "Enterprise Platform",
        status: "active",
        started_at: new Date(Date.now() - 86400000 * 180).toISOString(),
        amount: 8900,
      },
      {
        id: "sub-2",
        plan_name: "Priority builds add-on",
        status: "active",
        started_at: new Date(Date.now() - 86400000 * 90).toISOString(),
        amount: 1200,
      },
    ],
    payments: [
      {
        id: "pay-1",
        amount: 8900,
        status: "succeeded",
        method: "card",
        created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
        invoice_id: "inv-9001",
      },
    ],
    invoices: [
      {
        id: "inv-9001",
        number: "INV-9001",
        total: 8900,
        status: "paid",
        paid_at: new Date(Date.now() - 86400000 * 30).toISOString(),
        created_at: new Date(Date.now() - 86400000 * 31).toISOString(),
      },
    ],
    cart: { items_count: 0, promo_code: null },
    contact_messages: [
      {
        id: "cm-1",
        name: "Jordan Lee",
        email: "operations@northwind.mobile",
        subject: "HIPAA review packet",
        topic: "security",
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    ],
  },
  "demo-client-aurora": {
    summary: ADMIN_CLIENTS_DEMO[1]!,
    profile: {
      id: "demo-client-aurora",
      email: "growth@aurora.health",
      full_name: "Samira Patel",
      plan: "business",
      email_verified: true,
      created_at: ADMIN_CLIENTS_DEMO[1]!.created_at,
      location: "London, UK",
      website: "https://aurora.example",
    },
    apps: [
      {
        id: "demo-app-c",
        name: "Aurora Member",
        package_name: "com.aurora.member",
        status: "active",
        created_at: new Date(Date.now() - 86400000 * 40).toISOString(),
      },
    ],
    builds: [],
    subscriptions: [
      {
        id: "sub-a",
        plan_name: "Business",
        status: "active",
        started_at: new Date(Date.now() - 86400000 * 80).toISOString(),
        amount: 290,
      },
    ],
    payments: [],
    invoices: [],
    cart: { items_count: 1, promo_code: "WELCOME10" },
    contact_messages: [],
  },
};
